# Profiles Config for Clash Verge

current: RzDf2xvJSYnN
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1765036143
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1765036143
- uid: mLK6g2aIEY98
  type: merge
  name: null
  file: mLK6g2aIEY98.yaml
  updated: 1765036266
- uid: sbiOaqsLSHAJ
  type: script
  name: null
  file: sbiOaqsLSHAJ.js
  updated: 1765036266
- uid: rb4EjkrahB7V
  type: rules
  name: null
  file: rb4EjkrahB7V.yaml
  updated: 1765036266
- uid: pt2d6NHwQBoS
  type: proxies
  name: null
  file: pt2d6NHwQBoS.yaml
  updated: 1765036266
- uid: g2XN5g7KiEuk
  type: groups
  name: null
  file: g2XN5g7KiEuk.yaml
  updated: 1765036266
- uid: RMKVRhbQsu22
  type: remote
  name: 一元机场.VIP
  file: RMKVRhbQsu22.yaml
  url: https://b4ckkxagxaxxefca.duboji.vip/search?token=7f39c140eb479cfb3f31d944df5b208a
  selected:
  - name: GLOBAL
    now: 美国LisaSFO-rl(主力A)
  - name: 一元机场.VIP
    now: 日本02-手机畅享
  extra:
    upload: 1368878
    download: 11694581
    total: 107374182400
    expire: 1775534251
  updated: 1771039694
  option:
    update_interval: 1440
    merge: mLK6g2aIEY98
    script: sbiOaqsLSHAJ
    rules: rb4EjkrahB7V
    proxies: pt2d6NHwQBoS
    groups: g2XN5g7KiEuk
- uid: moLnQ9rZKWB5
  type: merge
  name: null
  file: moLnQ9rZKWB5.yaml
  updated: 1784117095
- uid: s0bhPSbRWgiB
  type: script
  name: null
  file: s0bhPSbRWgiB.js
  updated: 1784117095
- uid: rxz3a4YQEPwM
  type: rules
  name: null
  file: rxz3a4YQEPwM.yaml
  updated: 1784117095
- uid: pUiNYbT3SdNn
  type: proxies
  name: null
  file: pUiNYbT3SdNn.yaml
  updated: 1784117095
- uid: gQC0uO2dkiZD
  type: groups
  name: null
  file: gQC0uO2dkiZD.yaml
  updated: 1784117095
- uid: RWyRGINKqWzJ
  type: remote
  name: cf608a65161c9b63090989c5add8485ed2bfb9c6aa00e37a
  file: RWyRGINKqWzJ.yaml
  url: https://my.tuuii.com/api/sub/cf608a65161c9b63090989c5add8485ed2bfb9c6aa00e37a
  selected:
  - name: 🚀 节点选择
    now: US-TG1
  updated: 1790657426
  option:
    merge: moLnQ9rZKWB5
    script: s0bhPSbRWgiB
    rules: rxz3a4YQEPwM
    proxies: pUiNYbT3SdNn
    groups: gQC0uO2dkiZD
- uid: mQLpQTnA1wnc
  type: merge
  name: null
  file: mQLpQTnA1wnc.yaml
  updated: 1790657447
- uid: sUVNgMWvYLUE
  type: script
  name: null
  file: sUVNgMWvYLUE.js
  updated: 1790657447
- uid: rJ8aNlqJFwvW
  type: rules
  name: null
  file: rJ8aNlqJFwvW.yaml
  updated: 1790657447
- uid: pyuaQwMCWWvQ
  type: proxies
  name: null
  file: pyuaQwMCWWvQ.yaml
  updated: 1790657447
- uid: gW4ibQaMnAwz
  type: groups
  name: null
  file: gW4ibQaMnAwz.yaml
  updated: 1790657447
- uid: RzDf2xvJSYnN
  type: remote
  name: 良心云
  file: RzDf2xvJSYnN.yaml
  url: https://liangxin.xyz/api/v1/liangxin?OwO=4db5733dd040467a61dd3904cd70ebe7
  selected:
  - name: 良心云
    now: 🇯🇵日本高速02|BGP|CUCM
  extra:
    upload: 5389012167
    download: 98535435955
    total: 1099511627776
    expire: 0
  updated: 1791422879
  option:
    update_interval: 1440
    merge: mQLpQTnA1wnc
    script: sUVNgMWvYLUE
    rules: rJ8aNlqJFwvW
    proxies: pyuaQwMCWWvQ
    groups: gW4ibQaMnAwz
